services:
  manageit:
    container_name: manageit
    build:
      context: ../
      dockerfile: docker/Dockerfile
    working_dir: /manageit
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    networks:
      - sql

networks:
  sql:
    name: common
    external: true
