# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: manageit server ci

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: starting server
      run: |
        docker compose -f docker/docker-compose.yaml down
        docker compose -f docker/docker-compose.yaml up -d
